version: "3.9"

services:

  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_DB: "hack-fs"
      POSTGRES_USER: "hack_fs_app"
      POSTGRES_PASSWORD: "hack_fs_app_password"

  hack-fs-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      HACK_FS_DATABASE_URL: "jdbc:postgresql://postgres:5432/hack-fs"
      HACK_FS_DATABASE_USER: "hack_fs_app"
      HACK_FS_DATABASE_PASSWORD: "hack_fs_app_password"
      HACK_FS_EMAIL_USERNAME: ""
      HACK_FS_EMAIL_PASSWORD: ""